import { cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = process.cwd();
const srcDir = join(root, "src");
const appDir = join(srcDir, "app");
const contentDir = join(srcDir, "content");
const stylesDir = join(srcDir, "styles");
const outputDir = join(root, "public", "custom");
const outputAppDir = join(outputDir, "app");
const outputContentDir = join(outputDir, "content");

async function listFiles(dir, extension) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await listFiles(path, extension));
    } else if (entry.name.endsWith(extension)) {
      files.push(path);
    }
  }

  return files.sort((a, b) => a.localeCompare(b));
}

await mkdir(outputDir, { recursive: true });

const cssFiles = await listFiles(stylesDir, ".css");
const css = await Promise.all(cssFiles.map(async (file) => {
  const relative = file.replace(stylesDir, "src/styles").replaceAll("\\", "/");
  return `/* ${relative} */\n${await readFile(file, "utf8")}`;
}));

await writeFile(
  join(outputDir, "site.css"),
  `/* Generated from src/styles. Do not edit this file directly. */\n\n${css.join("\n\n")}\n`
);

await rm(outputAppDir, { recursive: true, force: true });
await cp(appDir, outputAppDir, { recursive: true });
await rm(outputContentDir, { recursive: true, force: true });
await cp(contentDir, outputContentDir, { recursive: true });
await writeFile(
  join(outputDir, "site.js"),
  `// Generated from src/app. Do not edit this file directly.\nimport "./app/main.js";\n`
);

console.log(`Built ${join(outputDir, "site.css")}`);
console.log(`Built ${join(outputDir, "site.js")}`);
